### PR TITLE
Show an update notification

### LINKED ISSUE #24: [Question] Update available notification
Hi! First off, awesome work on JellyAmp! I use it on a nearly daily basis 😄 

I was wondering, would you accept an PR with where a notification would be shown if a newer release of JellyAmp is available on Github ?

### PR DESCRIPTION
**Pull request by sandervankasteel**
This PR will introduce the feature, to show an inline toast message when a new release (ie. tag) on Github is available.

It also introduces the possibility to disable the 'check for updates' feature.

I've added a NPM dependency for compare-version(https://www.npmjs.com/package/compare-versions), this library does all the heavy lifting with regards to comparing version numbers. 

### Preview of the toast message 

Screenshot 2020-12-27 at 21 52 52

### Check for updates switch, in the settings overview
Screenshot 2020-12-27 at 21 53 13

## Notes
I've had to add the following line to the `preload.js`, since `process.env` inside a Vue component wouldn't return all the available properties. So I worked around it, by using `window._` variable.
`window._app_version = process.env.npm_package_version;`

This PR closes #24

### CODE REVIEW

**Comment by m0ngr31** [comment]
It might be easier to do something builtin to Electron Builder (since I'm using that already): https://www.electron.build/auto-update.html#module_electron-updater

**Comment by sandervankasteel** [comment]
@m0ngr31 Yeah that might be a better idea, since it has all the functionalities inside it. 😄 

I will change my implementation to use electron's own auto-update. 👍

**Comment by sandervankasteel** [comment]
Hi @m0ngr31, I've just finished changing my update notification by using electron-updater. 

There is 1 gotcha, if you want to test this manually, you manually need to copy the `dev-app-update.yml` into the `dist_electron` directory.

**Comment by m0ngr31** [comment]
If you want to clean up your comments, I'll get it merged!

**Comment by sandervankasteel** [comment]
I'm sorry but I am a bit confused. What do you mean with "clean up your comments" ? Do you mean Git commit squashing @m0ngr31 ?

**Comment by m0ngr31** [comment]
Sorry, it looked like there was some comments in your code that didn't need to be there. Maybe my browser window was stale.

**Comment by m0ngr31** [comment]
I added a huge change tonight. Do you might fixing the merge conflicts and I'll do a new release with this?

**Comment by sandervankasteel** [comment]
Cool! Yes, I will resolve the merge conflict :)

**Comment by m0ngr31** [comment]
I fixed it locally w/ #32

**Pull request closed without merging**
